# /frontend/nginx.conf
server {
    listen 80;
    
    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        # React Router 등 SPA 라우팅을 위한 핵심 설정
        try_files $uri $uri/ /index.html;
    }

    # 백엔드 API 포워딩 (필요시 사용, 현재는 프론트에서 직접 호출하므로 필수 아님)
    # location /api {
    #     proxy_pass http://express-back:8000;
    # }

    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }
}